3.20.2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -108,12 +108,12 @@ jobs:
         with:
           node-version: 22
 
-      - name: Prepare for app notarization
-        if: startsWith(matrix.os, 'macos')
-        # Import Apple API key for app notarization on macOS
-        run: |
-          mkdir -p ~/private_keys/
-          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
+#      - name: Prepare for app notarization
+#        if: startsWith(matrix.os, 'macos')
+#        # Import Apple API key for app notarization on macOS
+#        run: |
+#          mkdir -p ~/private_keys/
+#          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
 
 
       - name: Build/release Electron app
@@ -132,9 +132,15 @@ jobs:
           mac_certs_password: ${{ secrets.mac_certs_password }}
         env:
           # macOS notarization API key
-          API_KEY_ID: ${{ secrets.api_key_id }}
-          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
+          #API_KEY_ID: ${{ secrets.api_key_id }}
+          #API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
+          APPLE_ID: ${{ secrets.APPLE_ID }}
+          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
+          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
 
+      - name: Show notarization-error.log
+        if: failure()
+        run: cat dist-darwin/**/notarization-error.log || echo "No notarization-error.log found"
 
   linux:
     needs: "create-release"
